
#TODO: Add Auth Service + Broker API

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - authdb:mysql
  ports:
    - 10080:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: raptor
    MYSQL_DATABASE: raptor

authdb:
  image: mariadb
  ports:
    - 3306:3306
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: raptor
