version: "2"

networks:
  raptor_net:
    driver: bridge

services:

  raptor-http-api:
    build: ./raptor-http-api
    container_name: raptor-http-api
    ports:
      - 8080:8080
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - elasticsearch1
      - couchbase1
    networks:
      - raptor_net

  raptor-broker:
    build: ./raptor-broker
    container_name: raptor-broker
    ports:
      - 1883:1883
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - elasticsearch1
    networks:
      - raptor_net

  raptor-auth-service:
    build: ./raptor-auth-service
    container_name: raptor-auth-service
    ports:
      - 8090:8090
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - mariadb
    networks:
      - raptor_net

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
    networks:
      - raptor_net

  couchbase1:
    image: couchbase/server
    volumes:
      - ./data/couchbase1:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    networks:
      - raptor_net

  elasticsearch1:
    image: elasticsearch:5
    command: elasticsearch -Des.network.host=0.0.0.0 -Des.cluster.name="raptor" -Des.node.name="elasticsearch1"
    volumes:
      - ./data/elasticsearch1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - raptor_net
