
#TODO: Add Auth Service + Broker API

phpmyadmin:
  image: phpmyadmin
  links:
    - authdb:mysql
  ports:
    - 10080:8080
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: raptor

authdb:
  image: mariadb
  ports:
    - 3306:3306
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: raptor
