
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raptor
    username: root
    password: raptor
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
    
  jpa:
    show-sql: true

  # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: update

      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
    # stripped before adding them to the entity manager)
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect    

  logging:
    level:
      # org.springframework.security: DEBUG


---

jwt:
  
  header: Authorization
  
  # A secret used application wide for login token generation, keep it really secret
  secret: Voi che vivete sicuri Nelle vostre tiepide case
  
  # TTL in seconds, 1800 = 30 minutes
  expiration: 1800
  
  route:
    authentication:
      path: login
      refresh: refresh
---

raptor:
  admin:
    enabled: true
    username: admin
    password: admin
    email: admin@raptor.local
