spring:
  application:
    name: jdbc
logging:
  level:
    # org.springframework.security: DEBUG

## Mysql support
#  jpa:
#    hibernate:
#      # possible values: validate | update | create | create-drop
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:mysql://localhost/raptor
#    username: root
#    password: raptor
#    driver-class-name: com.mysql.jdbc.Driver

---

jwt:
  header: Authorization
  secret: raptor
  expiration: 604800
  route:
    authentication:
      path: login
      refresh: refresh

---

spring:
  profiles: client
server:
  port: 8081