# define the type of auth: token, allow_all
type: allow_all
cache: memory
token:
  truststore:
    path: ~/truststore
    password: passwd
  checkUrl: https://raptorbox.eu/api/token/check
  syncUrl: https://raptorbox.eu/api/device/sync
