#auth: token, allow_all
type: token
#cache: memory, none
cache: memory
token:
  truststore:
    path: /etc/raptor/truststore
    password: passwd
  checkUrl: http://localhost:8090/auth/check
  syncUrl: http://localhost:8090/auth/sync
