
# the message router adapter, in charge of serving topic/message formatting
# - default
router: default

# The broker client instance:
# - mqtt
client: mqtt

mqtt:
  username: system
  password: system123
  uri: tcp://localhost:1883
