
type: jdbc

jdbc:
  connection: jdbc:sqlite:~/tmp/raptor.sqlite
  tables:
    objects:
      name: objects
      fields:
        objectId: string
        userId: string

    data:
      name: data
      fields:
        lastUpdate: int
        objectId: string
        userId: string
        streamId: string

    actuations:
      name: actions
      fields:
        objectId: string
        userId: string
        actionId: string

couchbase:
  nodes:
    - raptor.local
  username: admin
  password: password
  bucketDefaults:
    password: ""
    quota: 360
    replica: 0
    indexReplica: false
    enableFlush: false

  bucketsIndex:
    objects:
      - [userId]
    data:
      - [userId]
      - [userId, streamId]
      - [userId, objectId]
      - [userId, objectId, streamId]
    actuations:
      - [userId]

  buckets:
    # Configure couchbase bucket name
    objects: raptor-objects
    data: raptor-data
    actuations: raptor-actions
