
type: couchbase
couchbase:
  nodes:
    - raptor.local

  username: Administrator
  password: password

  bucketDefaults:
    password: ""
    quota: 120
    replica: 0
    indexReplica: false
    enableFlush: false

  buckets:
    # Configure couchbase bucket name
    objects: serviceobjects
    data: soupdates
    actuations: actuations
